name: ASP.NET Deploy to IIS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output "C:\Users\nares\Documents\BOOKGA\ReadBook"

    - name: Deploy to IIS
      run: |
        iisreset /stop
        powershell -Command "
        $localBin = 'C:\Users\nares\Documents\BOOKGA\ReadBook\bin'
        $iisBin = 'C:\IISPublish\ReadBook.com\bin'

        # Ensure IIS bin directory exists
        if (!(Test-Path $iisBin)) {
            New-Item -ItemType Directory -Force -Path $iisBin
        }

        # Get today's date
        $today = (Get-Date).Date

        # Get the list of files modified today
        $filesToCopy = Get-ChildItem -Path $localBin -Recurse | Where-Object { $_.LastWriteTime.Date -eq $today }

        # Copy files modified today from local bin to IIS bin using xcopy
        foreach ($file in $filesToCopy) {
            $sourceFile = $file.FullName
            $destinationFile = Join-Path $iisBin $file.Name

            # Use xcopy to copy the file, overwriting if it exists
            Write-Host 'Copying file: ' $sourceFile
            xcopy $sourceFile $destinationFile /Y
        }
        Write-Host 'Files modified today have been copied to IIS bin.'
        "
        iisreset /start
